Repository triton-inference-server/fil_backend, pull requests merged in 2021-07, with the labels that each got.

#102 Provide instructions for pulling Triton container
  README.md
Labels: 3 - Ready for review

#103 Test CPU-only inference without visible GPU
  .gitignore
  qa/run_tests.sh
Labels: 3 - Ready for review

#92 Remove guidance in docs on limit for large input arrays
  README.md
  qa/L0_e2e/generate_example_model.py
  qa/run_tests.sh
Labels: 3 - Ready for review

#115 Loosen tolerance for mismatched classifications
  qa/L0_e2e/test_model.py
Labels: 3 - Ready for review, bug

#112 Triton FIL backend XGBoost notebook and README
  .gitignore
  notebooks/README.md
  notebooks/simple_xgboost_example.ipynb
Labels: 4 - Waiting on Author, enhancement

#116 Remove batch size preferences
  README.md
  qa/L0_e2e/generate_example_model.py
Labels: 3 - Ready for review, documentation

#117 Update references to latest released Triton version
  CMakeLists.txt
  README.md
  ops/Dockerfile
  ops/quick_build.sh
Labels: 4 - Waiting on Reviewer, enhancement
